package svc;

import java.util.ArrayList;

/**
 Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

 It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

 Find the pair of pentagonal numbers, Pj and Pk, for which their sum AND difference are pentagonal and
 D = |Pk − Pj| is minimised; what is the value of D?
 * Created by sauer on 7/23/16.
 */
class Project_44 extends Project {
    private Boolean answerFound = false;
    private ArrayList<Integer> discoveredPentagonalNumbers = new ArrayList<>();
    private String answer = null;
    public void execute(){
        addPentagonalNumber();
        addPentagonalNumber();
        while (!answerFound) {
            addPentagonalNumber();
            for (int x = 0; x < discoveredPentagonalNumbers.size(); x++) {
                if (isPentagonal(discoveredPentagonalNumbers.get(0)-discoveredPentagonalNumbers.get(x))) {
                    if(isPentagonal(discoveredPentagonalNumbers.get(0)+discoveredPentagonalNumbers.get(x))){
                        answerFound = true;
                        answer = "Answer:" + (discoveredPentagonalNumbers.size()) + ", " + (discoveredPentagonalNumbers.size()-x);
                    }
                }
            }

        }

        showMessage("Answer:" + answer) ;
    }

    private void addPentagonalNumber(){
        discoveredPentagonalNumbers.add(0,((discoveredPentagonalNumbers.size()+1)*(3*(discoveredPentagonalNumbers.size()+1)-1)/2));
    }

    private boolean isPentagonal(int num){
         return  (((Math.sqrt((24*num+1))+1))/6.0%1==0);
    }
}
